name: Single Headless Docker Build
run-name: Headless Docker Build for ${{ inputs.headless_type }} - ${{ inputs.factorio_version }}
on:
  workflow_dispatch: # For manual runs or version watcher events
    inputs:
      headless_type:
        description: 'Headless image version type to build'
        required: true
        type: choice
        options:
          - experimental
          - stable
      factorio_version:
        description: 'Factorio version to build against'
        required: true
        type: string
jobs:
  builder:
    name: Headless builder
    runs-on: ubuntu-latest
    concurrency: headlessBuild
    steps:
      - name: Verify headless type is an allowed value
        run: test "${{ inputs.headless_type }}" == experimental || test "${{ inputs.headless_type }}" == stable
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - id: validate
        name: Validate if this headless image for this Factorio version exists
        run: ./.github/workflows/scripts/validate_docker_tag.sh "${{ inputs.factorio_version }}" # Outputs `exists` as true/false
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - id: validateAlreadyDone
        name: Validate if the current headless image matches the current headless type image
        if: steps.validate.outputs.exists == 'true'
        run: ./.github/workflows/scripts/docker_image_equality.sh "${{ inputs.factorio_version }}" "${{ inputs.headless_type }}" # Outputs `equals` as true/false
      - name: Build and push headless image
        if: steps.validate.outputs.exists == 'false' || steps.validateAlreadyDone.outputs.equals == 'false'
        uses: docker/build-push-action@v3
        with:
          build-args: VERSION=${{ inputs.factorio_version }}
          push: true
          tags: |
            ${{ inputs.factorio_version }}
            ${{ inputs.headless_type }}
