name: Headless docker build, if needed
on:
  workflow_call:
    inputs:
      headless_type:
        description: 'Headless image version type to build'
        required: true
        type: string
      factorio_version:
        description: 'Factorio version to build against'
        required: true
        type: string
jobs:
  builder:
    name: Headless builder
    runs-on: ubuntu-latest
    steps:
      - name: Verify headless type is an allowed value
        run: test "${{ inputs.headless_type }}" == experimental || test "${{ inputs.headless_type }}" == stable
      - uses: actions/checkout@v3
      - id: validate
        name: Validate if this headless image for this Factorio version exists
        run: ./.github/workflows/scripts/validate_docker_tag.sh "${{ inputs.factorio_version }}" # Outputs `exists` as true/false
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - id: validateAlreadyDone
        name: Validate if the current headless image matches the current headless type image
        if: ${{ steps.validate.output.exists }} == 'true'
        run: ./.github/workflows/scripts/docker_image_equality.sh "${{ inputs.factorio_version }}" "${{ inputs.headless_type }}" # Outputs `equals` as true/false
      - name: Build and push headless image
        if: ${{ steps.validate.output.exists }} != 'true' || ${{ steps.validateAlreadyDone.output.equals }} != 'true'
        uses: docker/build-push-action@v3
        with:
          build-args: VERSION=${{ inputs.factorio_version }}
#          push: true
          tags: |
            ${{ inputs.factorio_version }}
            ${{ inputs.headless_type }}
